# Generated by Django 3.2.8 on 2023-06-30 07:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Category safe url')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='Product safe url')),
                ('images', models.ImageField(default='images/others/igor-lypnytskyi-PobecUzsK4c-unsplash.png', help_text='Upload a product image', upload_to='images/uploads/', verbose_name='image')),
                ('ingredient', models.TextField(blank=True, help_text='Not Required', verbose_name='ingredient')),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('price', models.IntegerField(error_messages={'name': {'max_length': 'The price must be between 0 and 999.99.'}}, help_text='Maximum 999.99', verbose_name='Regular price')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='Restaurant was visited')),
                ('in_stock', models.BooleanField(default=True, help_text='Change product availability', verbose_name='Product availability')),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_category', to='product.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vendors_products', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
