# Generated by Django 3.2.8 on 2023-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='images/site_images/food-dummy.jpg', help_text='Upload a product image', upload_to='images/uploads/store', verbose_name='image'),
        ),
    ]
