# Generated by Django 3.2.8 on 2023-06-30 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
        ('product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_quantity', models.CharField(max_length=250, null=True)),
                ('order_key', models.CharField(max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('billing_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address_info', to='account.address', verbose_name='address info')),
                ('delivery_instructions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delivery_info', to='checkout.deliveryoptions', verbose_name='delivery instructions')),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pay_option', to='checkout.paymentselections')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Reciept',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderedItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.orderreciept')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Ordered Item Details',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_order', to='order.orderreciept')),
            ],
            options={
                'verbose_name_plural': 'Checkout',
                'ordering': ['-created'],
            },
        ),
    ]
