# Generated by Django 3.2.8 on 2023-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='user_image',
            field=models.ImageField(default='images/site_images/profile.jpg', help_text='Upload a your image', upload_to='images/uploads/profile/', verbose_name='profile image'),
        ),
    ]
